inherit_from: configs/single_view_reconstruction/multi_view_supervision/ours_combined_pretrained.yaml
data:
  dataset_name: images
  path: media/demo/airplane
training:
  out_dir:  out/demo/airplane
generation:
  generation_dir: generation